###
GET http://localhost:3001/profile
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Imdvb2dsZSI6eyJpZCI6IjExODIzNzgzNDQwMzM5MjE2Mjk2NSIsIm5hbWUiOiJCZW4gQmVuIiwiZW1haWwiOiJwaGFzMHJ1a0BnbWFpbC5jb20ifSwiX2lkIjoiNjM1YzRiOWQ5ZDYzZjg3MDVhZTg2ZWFiIiwiX192IjowfSwiaWF0IjoxNjY2OTkzMDUzLCJleHAiOjE2NjY5OTY2NTN9.cpXWb6OJfbFUFdKeHH0rETLVHTL2sJLiyD8IorOAwdU
